version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/core.sn-boost.com
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  BeforeInstall:
    - location: scripts/BeforeInstallHook.sh
      timeout: 1000
  AfterInstall:
    - location: scripts/AfterInstallHook.sh
      timeout: 1000