<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $states = [
            [
                'name' => 'Alabama',
                'cities' => [
                    'Birmingham',
                    'Montgomery',
                    'Mobile',
                    'Huntsville',
                    'Tuscaloosa',
                    'Hoover',
                    'Dothan',
                    'Auburn',
                    'Decatur',
                    'Madison',
                    'Florence',
                    'Gadsden',
                    'Vestavia Hills',
                    'Prattville',
                    'Phenix City',
                    'Alabaster',
                    'Bessemer',
                    'Prichard',
                    'Opelika',
                    'Enterprise',
                    'Homewood',
                    'Athens',
                    'Northport',
                    'Anniston',
                    'Daphne',
                    'Pelham',
                    'Oxford',
                    'Albertville',
                    'Selma',
                    'Mountain Brook',
                    'Troy',
                    'Trussville',
                    'Center Point',
                    'Cullman',
                    'Talladega',
                    'Fairhope',
                    'Millbrook',
                    'Alexander City',
                    'Scottsboro',
                    'Ozark',
                    'Helena',
                    'Eufaula',
                    'Jasper',
                ]
            ],
            [
                'name' => 'Alaska',
                'cities' => [
                    'Anchorage',
                    'Fairbanks',
                    'Juneau',
                    'Sitka',
                    'Ketchikan',
                    'Wasilla',
                    'Kenai',
                    'Kodiak',
                    'Bethel',
                    'Palmer',
                    'Homer',
                    'Unalaska',
                    'Barrow',
                    'Soldotna',
                    'Valdez',
                    'Nome',
                    'Petersburg',
                    'Seward',
                    'Kotzebue',
                    'Wrangell',
                    'Dillingham',
                    'Cordova',
                    'North Pole',
                    'Houston',
                    'Craig',
                    'Hooper Bay',
                    'Akutan',
                    'Sand Point',
                    'Delta Junction',
                    'Chevak',
                    'King Cove',
                    'Klawock',
                    'Haines',
                    'Emmonak',
                    'Kake',
                    'Togiak',
                    'Unalakleet',
                    'Savoonga',
                    'St. Mary\'s',
                    'Galena',
                    'Nenana',
                    'Kotlik',
                    'New Stuyahok',
                    'Noorvik',
                    'Kivalina',
                    'Kiana',
                    'Golovin',

                ]
            ],
            [
                'name' => 'Arizona',
                'cities' => [
                    'Phoenix',
                    'Tucson',
                    'Mesa',
                    'Chandler',
                    'Glendale',
                    'Scottsdale',
                    'Gilbert',
                    'Tempe',
                    'Peoria',
                    'Surprise',
                    'Yuma',
                    'Avondale',
                    'Goodyear',
                    'Flagstaff',
                    'Buckeye',
                    'Lake Havasu City',
                    'Casa Grande',
                    'Sierra Vista',
                    'Maricopa',
                    'Oro Valley',
                    'Prescott',
                    'Bullhead City',
                    'Prescott Valley',
                    'Apache Junction',
                    'Marana',
                    'El Mirage',
                ]
            ],
            [
                'name' => 'Arkansas',
                'cities' => [
                    'Little Rock',
                    'Fort Smith',
                    'Fayetteville',
                    'Springdale',
                    'Jonesboro',
                    'North Little Rock',
                    'Conway',
                    'Rogers',
                    'Pine Bluff',
                    'Bentonville',
                    'Hot Springs',
                    'Benton',
                    'Texarkana',
                    'Sherwood',
                    'Jacksonville',
                    'Russellville',
                    'Bella Vista',
                    'West Memphis',
                    'Paragould',
                    'Cabot',
                    'Searcy',
                    'Van Buren',
                    'El Dorado',
                    'Maumelle',
                    'Bryant',
                    'Blytheville',
                    'Forrest City',
                    'Siloam Springs',
                    'Harrison',
                    'Mountain Home',
                ]
            ],
            [
                'name' => 'California',
                'cities' => [
                    'Los Angeles',
                    'San Diego',
                    'San Jose',
                    'San Francisco',
                    'Fresno',
                    'Sacramento',
                    'Long Beach',
                    'Oakland',
                    'Bakersfield',
                    'Anaheim',
                    'Santa Ana',
                    'Riverside',
                    'Stockton',
                    'Chula Vista',
                    'Irvine',
                    'Fremont',
                    'San Bernardino',
                    'Modesto',
                    'Fontana',
                    'Oxnard',
                    'Moreno Valley',
                    'Huntington Beach',
                    'Glendale',
                    'Santa Clarita',
                    'Garden Grove',
                    'Oceanside',
                    'Rancho Cucamonga',
                    'Santa Rosa',
                    'Ontario',
                    'Lancaster',
                ]
            ],
            [
                'name' => 'Colorado',
                'cities' => [
                    'Denver',
                    'Colorado Springs',
                    'Aurora',
                    'Fort Collins',
                    'Lakewood',
                    'Thornton',
                    'Arvada',
                    'Westminster',
                    'Pueblo',
                    'Centennial',
                    'Boulder',
                    'Greeley',
                    'Longmont',
                    'Loveland',
                    'Grand Junction',
                    'Broomfield',
                    'Castle Rock',
                    'Commerce City',
                    'Parker',
                    'Littleton',
                    'Northglenn',
                    'Brighton',
                    'Englewood',
                    'Wheat Ridge',
                    'Fountain',
                ]
            ],
            [
                'name' => 'Connecticut',
                'cities' => [
                    'Bridgeport',
                    'New Haven',
                    'Stamford',
                    'Hartford',
                    'Waterbury',
                    'Norwalk',
                    'Danbury',
                    'New Britain',
                    'Meriden',
                    'Bristol',
                    'West Haven',
                    'Milford',
                    'Middletown',
                    'Norwich',
                    'Shelton',
                    'Torrington',
                    'New London',
                    'Ansonia',
                    'Derby',
                    'Groton',
                ]
            ],
            [
                'name' => 'Georgia',
                'cities' => [
                    'Atlanta',
                    'Augusta',
                    'Columbus',
                    'Macon',
                    'Savannah',
                    'Athens',
                    'Sandy Springs',
                    'Roswell',
                    'Johns Creek',
                    'Albany',
                    'Warner Robins',
                    'Alpharetta',
                    'Marietta',
                    'Valdosta',
                    'Smyrna',
                    'Dunwoody',
                    'Rome',
                    'East Point',
                    'Milton',
                    'Gainesville',
                    'Hinesville',
                    'Peachtree City',
                    'Newnan',
                    'Dalton',
                    'Douglasville',
                    'Kennesaw',
                    'LaGrange',
                    'Statesboro',
                    'Lawrenceville',
                    'Duluth',
                ]
            ],
            [
                'name' => 'Hawaii',
                'cities' => [
                    'Honolulu',
                    'East Honolulu',
                    'Pearl City',
                    'Hilo',
                    'Kailua',
                    'Waipahu',
                    'Kaneohe',
                    'Mililani Town',
                    'Kahului',
                    'Ewa Gentry',
                    'Mililani Mauka',
                    'Kihei',
                    'Makakilo',
                    'Wahiawa',
                    'Schofield Barracks',
                ]
            ],
            [
                'name' => 'Idaho',
                'cities' => [
                    'Boise City',
                    'Meridian',
                    'Nampa',
                    'Idaho Falls',
                    'Pocatello',
                    'Caldwell',
                    'Coeur d\'Alene',
                    'Twin Falls',
                    'Lewiston',
                    'Post Falls',
                    'Rexburg',
                    'Moscow',
                    'Eagle',
                    'Kuna',
                    'Ammon',
                    'Chubbuck',
                    'Hayden',
                    'Mountain Home',
                    'Blackfoot',
                    'Garden City',
                    'Jerome',
                    'Burley',
                    'Star',
                ]
            ],
            [
                'name' => 'Illinois',
                'cities' => [
                    'Chicago',
                    'Aurora',
                    'Rockford',
                    'Joliet',
                    'Naperville',
                    'Springfield',
                    'Peoria',
                    'Elgin',
                    'Waukegan',
                    'Cicero',
                    'Champaign',
                    'Bloomington',
                    'Arlington Heights',
                    'Evanston',
                    'Decatur',
                    'Schaumburg',
                    'Bolingbrook',
                    'Palatine',
                    'Skokie',
                    'Des Plaines',
                    'Orland Park',
                    'Tinley Park',
                    'Oak Lawn',

                ]
            ],
            [
                'name' => 'Indiana',
                'cities' => [
                    'Indianapolis',
                    'Fort Wayne',
                    'Evansville',
                    'South Bend',
                    'Carmel',
                    'Bloomington',
                    'Fishers',
                    'Hammond',
                    'Gary',
                    'Muncie',
                    'Lafayette',
                    'Terre Haute',
                    'Kokomo',
                    'Anderson',
                    'Noblesville',
                    'Greenwood',
                    'Elkhart',
                    'Mishawaka',
                    'Lawrence',
                    'Jeffersonville',
                    'Columbus',
                    'Portage',
                    'New Albany',
                    'Richmond',
                    'Westfield',
                    'Valparaiso',
                    'Goshen',
                    'Michigan City',
                ]
            ],
            [
                'name' => 'Iowa',
                'cities' => [
                    'Des Moines',
                    'Cedar Rapids',
                    'Davenport',
                    'Sioux City',
                    'Iowa City',
                    'Waterloo',

                ]
            ],
            [
                'name' => 'Kansas',
                'cities' => [
                    'Wichita',
                    'Overland Park',
                    'Kansas City',
                    'Olathe',
                    'Topeka',
                    'Lawrence',
                    'Shawnee',
                    'Manhattan',
                    'Lenexa',
                    'Salina',
                    'Hutchinson'
                ]
            ],
            [
                'name' => 'Kentucky',
                'cities' => [
                    'Louisville',
                    'Lexington',
                    'Bowling Green',
                    'Owensboro',
                    'Covington',
                    'Richmond',
                    'Georgetown',
                    'Florence',
                    'Hopkinsville',
                ]
            ],
            [
                'name' => 'Louisiana',
                'cities' => [
                    'New Orleans',
                    'Baton Rouge',
                    'Shreveport',
                    'Lafayette',
                    'Lake Charles',
                    'Kenner',
                    'Bossier City',
                    'Monroe',
                    'Alexandria',

                ]
            ],
            [
                'name' => 'Maine',
                'cities' => [
                    'Portland',
                    'Lewiston',
                    'Bangor',
                    'South Portland',
                    'Auburn',
                ]
            ],
            [
                'name' => 'Maryland',
                'cities' => [
                    'Baltimore',
                    'Frederick',
                    'Rockville',
                    'Gaithersburg',
                    'Bowie',
                    'Hagerstown',
                    'Annapolis',
                    'College Park',
                    'Salisbury',

                ]
            ],
            [
                'name' => 'Massachusetts',
                'cities' => [
                    'Boston',
                    'Worcester',
                    'Springfield',
                    'Lowell',
                    'Cambridge',
                    'New Bedford',
                    'Brockton',
                ]
            ],
            [
                'name' => 'Michigan',
                'cities' => [
                    'Detroit',
                    'Grand Rapids',
                    'Warren',
                    'Sterling Heights',
                    'Ann Arbor',
                    'Lansing',
                    'Flint',

                ]
            ],
            [
                'name' => 'Minnesota',
                'cities' => [
                    'Minneapolis',
                    'Saint Paul',
                    'Rochester',
                    'Duluth',
                    'Bloomington',
                    'Brooklyn Park',
                    'Plymouth',
                    'Saint Cloud',
                    'Eagan',
                    'Woodbury',
                ]
            ],
            [
                'name' => 'Mississippi',
                'cities' => [
                    'Jackson',
                    'Gulfport',
                    'Southaven',
                    'Hattiesburg',
                    'Biloxi',
                    'Meridian',
                    'Tupelo',
                    'Greenville',
                    'Olive Branch',
                    'Horn Lake',
                    'Clinton',
                    'Pearl',
                    'Madison',
                    'Starkville',

                ]
            ],
            [
                'name' => 'Missouri',
                'cities' => [
                    'Kansas City',
                    'Saint Louis',
                    'Springfield',
                    'Independence',
                    'Columbia',
                    'Saint Joseph',
                    'Lee\'s Summit',
                    'Saint Charles',
                    'Saint Peters',
                    'Florissant',
                    'Blue Springs',
                    'Chesterfield',
                    'Joplin',
                    'Jefferson City',
                    'Cape Girardeau',
                    'Oakville',
                    'Wildwood',
                    'University City',
                ]
            ],
            [
                'name' => 'Montana',
                'cities' => [
                    'Billings',
                    'Missoula',
                    'Great Falls',
                    'Bozeman',
                    'Butte',
                    'Helena',
                    'Kalispell',
                    'Havre',
                    'Anaconda',
                    'Miles City',
                    'Belgrade',
                    'Livingston',
                    'Laurel',
                    'Whitefish',
                    'Lewistown',
                    'Sidney',
                    'Glendive',
                    'Columbia Falls',
                    'Polson',
                    'Hamilton',
                    'Dillon',
                    'Hardin',
                    'Shelby',
                ]
            ],
            [
                'name' => 'Nebraska',
                'cities' => [
                    'Omaha',
                    'Lincoln',
                    'Bellevue',
                    'Grand Island',
                    'Kearney',
                    'Fremont',
                    'Hastings',
                    'North Platte',
                    'Norfolk',
                    'Columbus',
                    'Papillion',
                    'La Vista',
                    'Scottsbluff',
                    'South Sioux City',
                    'Beatrice',
                    'Lexington',
                ]
            ],
            [
                'name' => 'Nevada',
                'cities' => [
                    'Las Vegas',
                    'Henderson',
                    'Reno',
                    'North Las Vegas',
                    'Sparks',
                    'Carson City',
                    'Fernley',
                    'Elko',
                    'Mesquite',
                    'Boulder City',
                    'Fallon',
                    'Winnemucca',
                    'West Wendover',
                    'Ely',
                    'Yerington',
                    'Carlin',
                    'Lovelock',
                    'Wells',
                    'Caliente',
                ]
            ],
            [
                'name' => 'New Hampshire',
                'cities' => [
                    'Manchester',
                    'Nashua',
                    'Concord',
                    'Dover',
                    'Rochester',
                    'Salem',
                    'Derry',
                    'Keene',
                    'Portsmouth',
                    'Laconia',
                    'Claremont',
                    'Lebanon',
                    'Somersworth',
                    'Berlin',
                    'Franklin',
                    'Hudson',
                    'Newport',
                    'Littleton',
                    'Durham',
                    'Exeter',
                    'Hampton',
                    'Milford',
                ]
            ],
            [
                'name' => 'New Jersey',
                'cities' => [
                    'Newark',
                    'Jersey City',
                    'Paterson',
                    'Elizabeth',
                    'Edison',
                    'Woodbridge',
                    'Lakewood',
                    'Toms River',
                    'Hamilton',
                    'Trenton',
                    'Clifton',
                    'Camden',
                    'Brick',
                    'Cherry Hill',
                    'Passaic',
                    'Middletown',
                    'Union City',
                    'Old Bridge',
                    'Gloucester Township',
                    'East Orange',
                    'Bayonne',
                    'Franklin Township',
                    'North Bergen',
                    'Vineland',
                    'Union',
                    'Middlesex',
                    'Piscataway',
                    'New Brunswick',
                ]
            ],
            [
                'name' => 'New Mexico',
                'cities' => [
                    'Albuquerque',
                    'Las Cruces',
                    'Rio Rancho',
                    'Santa Fe',
                    'Roswell',
                    'Farmington',
                    'South Valley',
                    'Clovis',
                    'Hobbs',
                    'Alamogordo',
                    'Carlsbad',
                    'Gallup',
                    'Deming',
                    'Los Lunas',
                    'Chaparral',
                    'Sunland Park',
                    'Las Vegas',
                    'Portales',
                    'Los Alamos',
                    'North Valley',
                    'Artesia',
                    'Lovington',
                    'Silver City',
                    'Espanola',
                    'Anthony',
                    'Grants',
                ]
            ],
            [
                'name' => 'North Carolina',
                'cities' => [
                    'Charlotte',
                    'Raleigh',
                    'Greensboro',
                    'Durham',
                    'Winston-Salem',
                    'Fayetteville',
                    'Cary',
                    'Wilmington',
                    'High Point',
                    'Greenville',
                    'Asheville',
                    'Concord',
                    'Gastonia',
                    'Jacksonville',
                    'Chapel Hill',
                    'Rocky Mount',
                    'Burlington',
                    'Wilson',
                    'Huntersville',
                    'Kannapolis',
                    'Apex',
                    'Hickory',
                    'Goldsboro',
                    'Indian Trail',
                    'Mooresville',
                    'Wake Forest',
                    'Monroe',
                    'Salisbury',
                    'New Bern',
                    'Matthews',
                    'Thomasville',
                    'Sanford',
                    'Cornelius',
                    'Garner',
                    'Holly Springs',
                    'Statesville',
                    'Mint Hill',
                ]
            ],
            [
                'name' => 'North Dakota',
                'cities' => [
                    'Fargo',
                    'Bismarck',
                    'Grand Forks',
                    'Minot',
                    'West Fargo',
                    'Mandan',
                    'Dickinson',
                    'Jamestown',
                    'Williston',
                    'Wahpeton',
                    'Devils Lake',
                    'Valley City',
                    'Grafton',
                    'Beulah',
                    'Rugby',
                    'Horace',
                    'Hazen',
                    'Lincoln',
                    'Cavalier',
                    'Langdon',
                    'Oakes',
                    'Hillsboro',
                    'Watford City',
                    'Lisbon',
                    'Carrington',
                    'Mayville',
                    'New Town',
                    'Stanley',
                    'Park River',
                    'Ellendale',
                    'Bottineau',
                ]
            ],
            [
                'name' => 'Ohio',
                'cities' => [
                    'Columbus',
                    'Cleveland',
                    'Cincinnati',
                    'Toledo',
                    'Akron',
                    'Dayton',
                    'Parma',
                    'Canton',
                    'Youngstown',
                    'Lorain',
                    'Hamilton',
                    'Springfield',
                    'Kettering',
                    'Elyria',
                    'Lakewood',
                    'Cuyahoga Falls',
                    'Middletown',
                    'Euclid',
                    'Newark',
                    'Mansfield',
                    'Mentor',
                    'Beavercreek',
                    'Cleveland Heights',
                    'Strongsville',
                    'Dublin',
                    'Fairfield',
                    'Findlay',
                    'Warren',
                ]
            ],
            [
                'name' => 'Oklahoma',
                'cities' => [
                    'Oklahoma City',
                    'Tulsa',
                    'Norman',
                    'Broken Arrow',
                    'Lawton',
                    'Edmond',
                    'Moore',
                    'Midwest City',
                    'Enid',
                    'Stillwater',
                    'Muskogee',
                    'Bartlesville',
                    'Owasso',
                    'Shawnee',
                    'Yukon',
                    'Bixby',
                    'Ardmore',
                    'Ponca City',
                    'Jenks',
                    'Duncan',
                    'Mustang',
                    'Del City',
                    'Sapulpa',
                    'Sand Springs',
                    'El Reno',
                    'Bethany',
                    'Claremore',
                    'Altus',
                    'McAlester',
                    'Durant',
                    'Ada',
                    'Tahlequah',
                    'Chickasha',
                    'Glenpool',
                    'Miami',
                    'Choctaw',
                    'Woodward',
                    'Okmulgee',
                ]
            ],
            [
                'name' => 'Oregon',
                'cities' => [
                    'Portland',
                    'Eugene',
                    'Salem',
                    'Gresham',
                    'Hillsboro',
                    'Beaverton',
                    'Bend',
                    'Medford',
                    'Springfield',
                    'Corvallis',
                    'Albany',
                    'Tigard',
                    'Lake Oswego',
                    'Keizer',
                    'Grants Pass',
                    'Oregon City',
                    'McMinnville',
                    'Redmond',
                    'Tualatin',
                    'West Linn',
                    'Woodburn',
                    'Forest Grove',
                    'Newberg',
                    'Wilsonville',
                    'Roseburg',
                    'Klamath Falls',
                    'Ashland',
                    'Milwaukie',
                    'Sherwood',
                    'Happy Valley',
                    'Central Point',
                    'Canby',
                    'Hermiston',
                    'Lebanon',
                    'Pendleton',
                    'Dallas',
                    'Coos Bay',
                    'Troutdale',
                    'The Dalles',
                    'St. Helens',
                    'La Grande',
                ]
            ],
            [
                'name' => 'Pennsylvania',
                'cities' => [
                    'Philadelphia',
                    'Pittsburgh',
                    'Allentown',
                    'Erie',
                    'Reading',
                    'Scranton',
                    'Bethlehem',
                    'Lancaster',
                    'Harrisburg',
                    'Altoona',
                    'York',
                    'State College',
                    'Wilkes-Barre',
                    'Norristown',
                    'Chester',
                    'Bethel Park',
                    'Williamsport',
                    'Monroeville',
                    'Plum',
                    'Easton',
                    'Lebanon',
                    'Hazleton',
                    'Pottstown',
                    'New Castle',
                    'Chambersburg',
                    'Murrysville',
                    'West Mifflin',
                    'Johnstown',
                    'McKeesport',
                    'Carlisle',
                    'Phoenixville',
                    'Hermitage',
                    'Lansdale',
                    'Wilkinsburg',
                    'Hanover',
                    'Sharon',
                    'Indiana',
                    'Washington',
                    'St. Marys',
                    'Butler',
                    'Meadville',
                    'Sunbury',
                    'Greensburg',
                    'Lock Haven',
                    'Williamsport',
                    'Bloomsburg',
                    'Pottsville',
                    'Uniontown',
                    'Oil City',

                ]
            ],

            [
                'name' => 'Rhode Island',
                'cities' => [
                    'Providence',
                    'Warwick',
                    'Cranston',
                    'Pawtucket',
                    'East Providence',
                    'Woonsocket',
                    'Coventry',
                    'Cumberland',
                    'North Providence',
                    'South Kingstown',
                    'West Warwick',
                    'Johnston',
                    'North Kingstown',
                    'Newport',
                    'Bristol',
                    'Westerly',
                    'Smithfield',
                ]
            ],

            [
                'name' => 'South Carolina',
                'cities' => [
                    'Columbia',
                    'Charleston',
                    'North Charleston',
                    'Mount Pleasant',
                    'Rock Hill',
                    'Greenville',
                    'Summerville',
                    'Sumter',
                    'Goose Creek',
                    'Hilton Head Island',
                    'Florence',
                    'Spartanburg',
                    'Myrtle Beach',
                    'Aiken',
                    'Greer',
                    'Anderson',
                    'Mauldin',
                    'Greenwood',
                    'North Augusta',
                    'Easley',
                ]
            ],

            [
                'name' => 'South Dakota',
                'cities' => [
                    'Sioux Falls',
                    'Rapid City',
                    'Aberdeen',
                    'Brookings',
                    'Watertown',
                    'Mitchell',
                    'Yankton',
                    'Pierre',
                    'Huron',
                    'Vermillion',
                    'Spearfish',
                    'Brandon',
                    'Box Elder',
                    'Rapid Valley',
                    'Madison',
                    'Sturgis',
                    'Belle Fourche',
                    'Harrisburg',
                    'Tea',
                    'Hot Springs',
                    'Dell Rapids',
                    'Mobridge',
                    'Canton',
                    'Lead',
                    'Milbank',
                    'Pine Ridge',
                    'Winner',
                    'Sisseton',
                    'Hartford',
                    'Colonial Pine Hills',
                    'Flandreau',
                    'North Sioux City',
                    'Redfield',
                    'Custer',
                ]
            ],

            [
                'name' => 'Tennessee',
                'cities' => [
                    'Memphis',
                    'Nashville-Davidson',
                    'Knoxville',
                    'Chattanooga',
                    'Clarksville',
                    'Murfreesboro',
                    'Jackson',
                    'Johnson City',
                    'Franklin',
                    'Bartlett',
                    'Hendersonville',
                    'Kingsport',
                    'Collierville',
                    'Cleveland',
                    'Smyrna',
                    'Germantown',
                    'Brentwood',
                    'Columbia',
                    'La Vergne',
                    'Cookeville',
                    'Gallatin',
                    'Oak Ridge',
                    'Morristown',
                    'Maryville',
                    'Bristol',
                ]
            ],

            [
                'name' => 'Texas',
                'cities' => [
                    'Houston',
                    'San Antonio',
                    'Dallas',
                    'Austin',
                    'Fort Worth',
                    'El Paso',
                    'Arlington',
                    'Corpus Christi',
                    'Plano',
                    'Laredo',
                    'Lubbock',
                    'Garland',
                    'Irving',
                    'Amarillo',
                    'Grand Prairie',
                    'Brownsville',
                    'Pasadena',
                    'McKinney',
                    'Mesquite',
                    'McAllen',
                    'Killeen',
                    'Frisco',
                    'Waco',
                    'Carrollton',
                    'Denton',
                    'Midland',
                    'Abilene',
                    'Beaumont',
                    'Round Rock',
                    'Odessa',
                ]
            ],
            [
                'name' => 'Utah',
                'cities' => [
                    'Salt Lake City',
                    'West Valley City',
                    'Provo',
                    'West Jordan',
                    'Orem',
                    'Sandy',
                    'Ogden',
                    'St. George',
                    'Layton',
                    'Taylorsville',
                    'South Jordan',
                    'Lehi',
                    'Logan',
                    'Murray',
                    'Draper',
                    'Bountiful',
                    'Riverton',
                    'Roy',
                    'Spanish Fork',
                    'Pleasant Grove',
                    'Kearns',
                    'Cottonwood Heights',
                    'Tooele',
                    'Springville',
                    'Midvale',
                    'Herriman',
                    'Holladay',
                    'Clearfield',
                    'American Fork',
                    'Syracuse',
                    'South Salt Lake',
                    'Eagle Mountain',
                    'Clinton',
                    'Washington',
                    'Payson',
                    'Farmington',
                    'Brigham City',
                    'Saratoga Springs',
                    'North Ogden',
                ]
            ],
            [
                'name' => 'Vermont',
                'cities' => [
                    'Burlington',
                    'South Burlington',
                    'Rutland',
                    'Barre',
                    'Montpelier',
                    'Winooski',
                    'St. Albans',
                    'Newport',
                    'Vergennes',
                    'Bellows Falls',
                    'Swanton',
                    'Morrisville',
                    'Waterbury',
                    'Northfield',
                    'North Bennington',
                    'Poultney',
                    'Johnson',
                    'Enosburg Falls',
                    'Lyndonville',
                    'Ludlow',
                    'Jeffersonville',
                    'Manchester',
                    'Woodstock',
                    'Middlebury',
                    'Derby Line',
                ]
            ],
            [
                'name' => 'Virginia',
                'cities' => [
                    'Virginia Beach',
                    'Norfolk',
                    'Chesapeake',
                    'Richmond',
                    'Newport News',
                    'Alexandria',
                    'Hampton',
                    'Roanoke',
                    'Portsmouth',
                    'Suffolk',
                    'Lynchburg',
                    'Harrisonburg',
                    'Leesburg',
                    'Charlottesville',
                    'Danville',
                ]
            ],
            [
                'name' => 'Washington',
                'cities' => [
                    'Seattle',
                    'Spokane',
                    'Tacoma',
                    'Vancouver',
                    'Bellevue',
                    'Kent',
                    'Everett',
                    'Renton',
                    'Yakima',
                    'Federal Way',
                    'Spokane Valley',
                    'Bellingham',
                    'Kennewick',
                    'Auburn',
                    'Pasco',
                    'Marysville',
                    'Lakewood',
                    'Redmond',
                    'Shoreline',
                    'Richland',
                    'Kirkland',
                    'Burien',
                    'Sammamish',
                    'Olympia',
                    'Lacey',
                ]
            ],
            [
                'name' => 'West Virginia',
                'cities' => [
                    'Charleston',
                    'Huntington',
                    'Parkersburg',
                    'Morgantown',
                    'Wheeling',
                    'Weirton',
                    'Fairmont',
                    'Beckley',
                    'Martinsburg',
                    'Clarksburg',
                    'South Charleston',
                    'St. Albans',
                    'Vienna',
                    'Bluefield',
                    'Moundsville',
                    'Bridgeport',
                    'Oak Hill',
                    'Dunbar',
                    'Elkins',
                    'Nitro',
                    'Hurricane',
                    'Princeton',
                    'Buckhannon',
                    'New Martinsville',
                    'Keyser',
                ]
            ],
            [
                'name' => 'Wisconsin',
                'cities' => [
                    'Milwaukee',
                    'Madison',
                    'Green Bay',
                    'Kenosha',
                    'Racine',
                    'Appleton',
                    'Waukesha',
                    'Eau Claire',
                    'Oshkosh',
                    'Janesville',
                    'West Allis',
                    'La Crosse',
                    'Sheboygan',
                    'Wauwatosa',
                    'Fond du Lac',
                    'New Berlin',
                    'Wausau',
                    'Brookfield',
                    'Greenfield',
                    'Beloit',
                    'Franklin',
                    'Menomonee Falls',
                    'Oak Creek',
                    'Manitowoc',
                    'West Bend',
                ]
            ],
            [
                'name' => 'Wyoming',
                'cities' => [
                    'Cheyenne',
                    'Casper',
                    'Laramie',
                    'Gillette',
                    'Rock Springs',
                    'Sheridan',
                    'Green River',
                    'Evanston',
                    'Riverton',
                    'Jackson',
                    'Cody',
                    'Rawlins',
                    'Lander',
                    'Torrington',
                    'Powell',
                    'Douglas',
                    'Ranchettes',
                    'Worland',
                    'Buffalo',
                    'South Greeley',
                    'Fox Farm-College',
                    'Mills',
                    'Wheatland',
                    'Newcastle',
                    'Evansville',
                ]
            ],

        ];

        foreach ($states as $key => $state) {
            $stateId = DB::table('states')->insertGetId([
                'name' => $state['name'],
                'country_id' => 1
            ]);

            foreach ($state['cities'] as $key => $city) {
                DB::table('cities')->insert([
                    'name' => $city,
                    'states_id' => $stateId
                ]);
            }
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
};
